"use client";
import { FeatureFields } from "./feature-fields";
import { categories, type Category, type Attributes } from "@/lib/wardrobe";
import { scenes } from "@/lib/app-state";
export type Fields = { category: Category | ""; color: string; attributes?: Attributes };
export function ClothingFields({ value, change }: { value: Fields; change: (value: Fields) => void }) {
  const a = value.attributes ?? { confirmed: false };
  function attr(patch: Partial<Attributes>) { change({ ...value, attributes: { ...a, ...patch } }); }
  return <div className="field-grid"><label>类别<select value={value.category} onChange={e => change({ ...value, category: e.target.value as Category | "" })}><option value="">请选择</option>{categories.map(c => <option key={c}>{c}</option>)}</select></label><label>颜色<input value={value.color} maxLength={30} placeholder="例如：米白色" onChange={e => change({ ...value, color: e.target.value })}/></label><FeatureFields value={a} change={attributes=>change({...value,attributes})}/><details className="full-row"><summary>补充我确认的适用条件（选填）</summary><p className="hint">只填写你实际了解的信息。未确认时不会按这些属性评分。</p><div className="field-grid mt-3"><label>适用最低温度 ℃<input type="number" min="-50" max="60" value={a.minTemp ?? ""} onChange={e => attr({ minTemp: e.target.value === "" ? undefined : Number(e.target.value) })}/></label><label>适用最高温度 ℃<input type="number" min="-50" max="60" value={a.maxTemp ?? ""} onChange={e => attr({ maxTemp: e.target.value === "" ? undefined : Number(e.target.value) })}/></label><label>室外雨天<select value={a.rainSuitable === undefined ? "" : String(a.rainSuitable)} onChange={e => attr({ rainSuitable: e.target.value === "" ? undefined : e.target.value === "true" })}><option value="">未确认</option><option value="true">适合</option><option value="false">不适合</option></select></label><label>舒适度<select value={a.comfort ?? ""} onChange={e => attr({ comfort: e.target.value ? Number(e.target.value) : undefined })}><option value="">未确认</option>{[1,2,3,4,5].map(n => <option key={n} value={n}>{n} / 5</option>)}</select></label></div><div className="chips mt-3">{scenes.map(scene => <button type="button" key={scene} aria-pressed={a.scenes?.includes(scene) ?? false} onClick={() => attr({ scenes: a.scenes?.includes(scene) ? a.scenes.filter(s => s !== scene) : [...(a.scenes ?? []),scene] })}>{scene}</button>)}</div><label className="check-row"><input type="checkbox" checked={a.confirmed} onChange={e => attr({ confirmed: e.target.checked })}/>以上适用条件由我确认</label></details></div>;
}
